name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          if: ${{ github.event_name == 'push' }}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: sleepy-bastion-85491
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://sleepy-bastion-85491.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true